SAMPLE_RATE = 8000
CHUNK_MS = 20
BYTES_PER_CHUNK = int(SAMPLE_RATE * CHUNK_MS / 1000)
CHUNK_INTERVAL = CHUNK_MS / 1000
STT_BATCH_FRAMES = 2

VAD_POOL_SIZE = 8
VAD_CHECK_EVERY = 5
SILENCE_TIMEOUT = 0.7

SPECULATIVE_MIN_WORDS = 4
SPECULATIVE_MIN_CHARS = 20
SPECULATIVE_DEBOUNCE_SEC = 0.5
SPECULATIVE_WORD_OVERLAP = 0.70

LLM_STREAM_TIMEOUT_SEC = 20
MAX_CALL_DURATION_SEC = 3600

SYSTEM_PROMPT = """
Hello, this is Nova from NovaCare Health Insurance.
How can I assist you today?
"""